[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = true

[window]
opacity = 0.8

[window.padding]
x = 4
y = 4
